"""empty message

Revision ID: 47c35baa13ff
Revises: 190be02a032b
Create Date: 2018-04-26 06:46:22.824233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c35baa13ff'
down_revision = '190be02a032b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selfie', sa.Column('filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selfie', 'filename')
    # ### end Alembic commands ###
