"""empty message

Revision ID: c015d3fe525c
Revises: d7b217c20d9c
Create Date: 2018-03-22 05:55:15.218813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c015d3fe525c'
down_revision = 'd7b217c20d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gif_timestamp', table_name='gif')
    op.drop_table('gif')
    op.drop_index('ix_user_timestamp', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_selfie_timestamp', table_name='selfie')
    op.drop_table('selfie')
    op.drop_index('ix_giphyme_timestamp', table_name='giphyme')
    op.drop_table('giphyme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giphyme',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emotion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('selfe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gif_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gif_id'], [u'gif.id'], name=u'giphyme_gif_id_fkey'),
    sa.ForeignKeyConstraint(['selfe_id'], [u'selfie.id'], name=u'giphyme_selfe_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'giphyme_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'giphyme_pkey')
    )
    op.create_index('ix_giphyme_timestamp', 'giphyme', ['timestamp'], unique=False)
    op.create_table('selfie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('emotion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'selfie_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'selfie_pkey')
    )
    op.create_index('ix_selfie_timestamp', 'selfie', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('user_id_seq'::regclass)"), nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'user_pkey'),
    sa.UniqueConstraint('email', name=u'user_email_key'),
    sa.UniqueConstraint('username', name=u'user_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_user_timestamp', 'user', ['timestamp'], unique=False)
    op.create_table('gif',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emotion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'gif_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'gif_pkey')
    )
    op.create_index('ix_gif_timestamp', 'gif', ['timestamp'], unique=False)
    # ### end Alembic commands ###
